# ЛР1
## 7 вариант

### Задание:
Изучить работу конечных автоматов Мили и Мура. \
-- представить конечный автомат Мили и Мура таблицей переходов и выходов; \
-- построить таблицу выходов интерпретирующего автомата Мили для автомата Мура;\
-- представить конечные автоматы матрицей соединений.

In [1]:
# подключение библиотек
import pandas as pd
import numpy as np
import itertools
import random

In [2]:
#входные параметры
sigma = list([set('АБВГД'), set('01')])         # -- номера входов
ksi = list([set('01')]*3)                       # -- номера состояний
tau = list([set('01'), set('АБВГ'), set('01')]) # -- номера выходов

In [3]:
print("sigma:", sigma)
print("ksi:",ksi)
print("tau",tau)

sigma: [{'Б', 'А', 'В', 'Г', 'Д'}, {'0', '1'}]
ksi: [{'0', '1'}, {'0', '1'}, {'0', '1'}]
tau [{'0', '1'}, {'Б', 'А', 'В', 'Г'}, {'0', '1'}]

In [4]:
# входы
list_input = []
print("Входы:")
for element in itertools.product(*sigma):
    list_input.append(element)
    print(element)
    
# состояния
list_condition = []
print("\nСостояния:")
for element in itertools.product(*ksi):
    list_condition.append(element)
    print(element)
    
# выходы
list_output = []
print("\nВыходы:")
for element in itertools.product(*tau):
    list_output.append(element)
    print(element)

Входы:
('Б', '0')
('Б', '1')
('А', '0')
('А', '1')
('В', '0')
('В', '1')
('Г', '0')
('Г', '1')
('Д', '0')
('Д', '1')

Состояния:
('0', '0', '0')
('0', '0', '1')
('0', '1', '0')
('0', '1', '1')
('1', '0', '0')
('1', '0', '1')
('1', '1', '0')
('1', '1', '1')

Выходы:
('0', 'Б', '0')
('0', 'Б', '1')
('0', 'А', '0')
('0', 'А', '1')
('0', 'В', '0')
('0', 'В', '1')
('0', 'Г', '0')
('0', 'Г', '1')
('1', 'Б', '0')
('1', 'Б', '1')
('1', 'А', '0')
('1', 'А', '1')
('1', 'В', '0')
('1', 'В', '1')
('1', 'Г', '0')
('1', 'Г', '1')

## Формирование таблицы переходов для автоматов Мили и Мура

In [5]:
# функция генерации таблицы переходов для автоматов Мили и Мура
def tb_transition(list_input, list_condition):  
    table_transition = pd.DataFrame('0', index=range(len(list_input)),
                                    columns=[ ''.join(list_condition[i]) for i in range(len(list_condition))])
    
    # заполнение таблицы случайными состояниями
    for i in table_transition.columns:
        for j in range(len(list_input)):
            table_transition[i][j] = table_transition.columns[random.randint(0,len(list_condition)-1)]
            
    table_transition['row_name'] = pd.Series([''.join(list_input[i]) for i in range(len(list_input))],
                                             index=table_transition.index)
    
    return(table_transition)

In [6]:
# таблица переходов для автоматов Мили и Мура
_transition = tb_transition(list_input, list_condition)
_transition

   000  001  010  011  100  101  110  111 row_name
0  100  010  001  100  100  010  001  101       Б0
1  000  011  100  111  000  100  100  100       Б1
2  101  011  011  100  000  100  111  010       А0
3  110  110  100  110  011  100  101  101       А1
4  100  100  011  111  010  010  000  010       В0
5  001  101  011  101  010  000  101  010       В1
6  000  010  111  011  100  000  100  100       Г0
7  111  011  100  000  010  110  100  100       Г1
8  111  000  101  110  000  101  010  001       Д0
9  101  011  001  010  000  100  101  001       Д1

## Формирование таблицы выходов для автомата Мили

In [7]:
# функция генерации таблицы выходов для автомата Мили
def tb_output(list_input, list_condition, list_output):
    table_output = pd.DataFrame('0', index=range(len(list_input)),
                                    columns=[ ''.join(list_condition[i]) for i in range(len(list_condition))])
    
    # заполнение таблицы случайными выходами
    for i in table_output.columns:
        for j in range(len(list_input)):
            table_output[i][j] = ''.join(list_output[random.randint(0,len(list_output)-1)])
            
    table_output['row_name'] = pd.Series([''.join(list_input[i]) for i in range(len(list_input))],
                                             index=table_output.index)
    
    return(table_output)

In [8]:
# таблица выходов для автомата Мили
_output = tb_output(list_input, list_condition, list_output)
_output

   000  001  010  011  100  101  110  111 row_name
0  0Б0  0А0  0Б0  1Г0  0В1  0В1  0А0  1А0       Б0
1  0Б0  0Г1  0Г0  0Г1  1А0  0Г1  1А1  0Г1       Б1
2  0А0  1Б0  0А0  1Б0  1В0  0А0  1Б1  0Б1       А0
3  1Г0  0В0  0В1  1Б1  0Г0  0Г0  0А1  1Б0       А1
4  0Б0  1В1  0Г1  1А1  0Б0  0А0  1Б1  1Г1       В0
5  0А1  0Г0  0В0  1В1  0Б1  0Г1  0В0  1А0       В1
6  1А0  1Б0  0Б0  0Б1  0В1  1В1  1В0  0А1       Г0
7  1Г0  1А1  1Б1  1В1  0В1  1Б1  1А0  0Б0       Г1
8  0Б1  0Г1  0Г0  0А0  1Г1  1Г0  0А0  0Г0       Д0
9  1В0  1Б0  0А0  0Б1  0А0  0В0  0В1  1А0       Д1

## Формирование отмеченной таблицы переходов для автомата Мура

In [9]:
# функция для составления отмеченной таблицы переходов для автомата Мура
def tb_marked(_transition, list_output):
    table_marked = _transition.copy(deep=True)
    row = []
    
    [row.append(''.join(list_output[random.randint(0,len(list_output)-1)]))
                    for i in range(len(_transition.columns)-1)]
    row.append('y1y2y3')
    table_marked.loc[_transition.shape[0]] = row
    
    return(table_marked)

In [18]:
# отмеченная таблица переходов для автомата Мура
_marked = tb_marked(_transition, list_output)
_marked

    000  001  010  011  100  101  110  111 row_name
0   100  010  001  100  100  010  001  101       Б0
1   000  011  100  111  000  100  100  100       Б1
2   101  011  011  100  000  100  111  010       А0
3   110  110  100  110  011  100  101  101       А1
4   100  100  011  111  010  010  000  010       В0
5   001  101  011  101  010  000  101  010       В1
6   000  010  111  011  100  000  100  100       Г0
7   111  011  100  000  010  110  100  100       Г1
8   111  000  101  110  000  101  010  001       Д0
9   101  011  001  010  000  100  101  001       Д1
10  1Б0  1В1  0Б1  1Б1  1В0  1Г0  1Г0  1Г1   y1y2y3

## Формирование таблицы выходов для интерпретирующего автомата Мили

In [35]:
# функция для составления таблицы выходов интерпретирующего автомата Мили
def tb_interpreter_out(_transition, _output, _marked):
    table_interpreter_out = _output.copy(deep=True)
    
    for i in _transition.columns[0:_transition.columns.shape[0]-1]:
        for j in range(_transition.shape[0]):
            if _output[i][j] == _marked[str(_transition[i][j])][_marked.shape[0]-1]:
                continue
            else: 
                table_interpreter_out[i][j] = 'x'
    
    return(table_interpreter_out)

In [36]:
# таблица выходов интерпретирующего автомата Мили
tb_interpreter_out(_transition, _output, _marked)

   000 001 010  011  100  101  110  111 row_name
0    x   x   x    x    x    x    x    x       Б0
1    x   x   x    x    x    x    x    x       Б1
2    x   x   x    x    x    x    x  0Б1       А0
3  1Г0   x   x    x    x    x    x    x       А1
4    x   x   x    x    x    x    x    x       В0
5    x   x   x    x  0Б1    x    x    x       В1
6    x   x   x    x    x    x  1В0    x       Г0
7    x   x   x    x    x    x    x    x       Г1
8    x   x   x    x    x  1Г0    x    x       Д0
9    x   x   x  0Б1    x    x    x    x       Д1

## Формирование матрицы соединений конечного автомата

In [192]:
# функция для составления матрицы соединений конечного автомата
def tb_compound(_transition, _output):
    table_compound = pd.DataFrame('0', index=range(_transition.shape[1]-1),
                                    columns=_transition.columns)
    for i in range(table_compound.shape[0]):
        table_compound['row_name'][i] = table_compound.columns[i]
        
    for i in table_compound.columns[0:table_compound.columns.shape[0]-1]:
        for j in range(table_compound.shape[0]):
            cell = _transition.index[_transition[i] == 
                        table_compound[ table_compound.columns[table_compound.shape[1]-1] ][j]]
            if len(cell) != 0:
                table_compound[i][j] = '';
                for k in range(len(cell)):
                    table_compound[i][j] += _output[_output.columns[_output.shape[1]-1]][cell[k]] + \
                            '/' + _output[i][cell[k]]
                    if k != len(cell)-1:
                        table_compound[i][j] += ' v '
    
    return(table_compound)

In [193]:
# матрица соединений конечного автомата
tb_compound(_transition, _output)

,000,001,010,011,100,101,110,111,row_name
0,Б1/0Б0 v Г0/1А0,Д0/0Г1,0,Г1/1В1,Б1/1А0 v А0/1В0 v Д0/1Г1 v Д1/0А0,В1/0Г1 v Г0/1В1,В0/1Б1,0,000
1,В1/0А1,0,Б0/0Б0 v Д1/0А0,0,0,0,Б0/0А0,Д0/0Г0 v Д1/1А0,001
2,0,Б0/0А0 v Г0/1Б0,0,Д1/0Б1,В0/0Б0 v В1/0Б1 v Г1/0В1,Б0/0В1 v В0/0А0,Д0/0А0,А0/0Б1 v В0/1Г1 v В1/1А0,010
3,0,Б1/0Г1 v А0/1Б0 v Г1/1А1 v Д1/1Б0,А0/0А0 v В0/0Г1 v В1/0В0,Г0/0Б1,А1/0Г0,0,0,0,011
4,Б0/0Б0 v В0/0Б0,В0/1В1,Б1/0Г0 v А1/0В1 v Г1/1Б1,Б0/1Г0 v А0/1Б0,Б0/0В1 v Г0/0В1,Б1/0Г1 v А0/0А0 v А1/0Г0 v Д1/0В0,Б1/1А1 v Г0/1В0 v Г1/1А0,Б1/0Г1 v Г0/0А1 v Г1/0Б0,100
5,А0/0А0 v Д1/1В0,В1/0Г0,Д0/0Г0,В1/1В1,0,Д0/1Г0,А1/0А1 v В1/0В0 v Д1/0В1,Б0/1А0 v А1/1Б0,101
6,А1/1Г0,А1/0В0,0,А1/1Б1 v Д0/0А0,0,Г1/1Б1,0,0,110
7,Г1/1Г0 v Д0/0Б1,0,Г0/0Б0,Б1/0Г1 v В0/1А1,0,0,А0/1Б1,0,111